/**
 * Quiz API route — POST /api/quiz
 *
 * Accepts a 5-answer quiz submission, returns 2–3 personalised treatment
 * recommendations generated by Gemini (`gemini-2.5-flash`) with a
 * schema-enforced JSON response. Falls back to lib/quiz-fallback.ts on any
 * provider failure or missing key. Rate-limited per IP at 10 req/min.
 *
 * Security posture (per CLAUDE.md §5):
 *  - GEMINI_API_KEY is server-side only. Never logged.
 *  - Request body validated with Zod; unknown fields rejected.
 *  - Per-string length cap (200 chars) prevents payload-stuffing abuse.
 *  - Rate limit returns 429 (distinct from fallback's 200 + meta.fallback).
 *  - Provider errors never leak to the client. Generic fallback on any throw.
 *  - No stack traces, no API echoes. Server logs only.
 */

import { NextResponse, type NextRequest } from "next/server";
import { GoogleGenAI, Type } from "@google/genai";
import { z } from "zod";

import { postLeadToAirtable } from "@/lib/airtable";
import { getFallbackRecommendations } from "@/lib/quiz-fallback";

// Force Node runtime: Edge would expose slightly different request semantics
// and isn't needed; we want full Node APIs for the SDK.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// ---------------------------------------------------------------------------
// Input validation
// ---------------------------------------------------------------------------

// Allowlist of exact Q1–Q5 strings from PRD §6.1. Keeps the model from being
// guided by typos or off-distribution inputs.
const Q1_VALUES = [
  "Fine lines & wrinkles",
  "Loss of volume",
  "Skin texture & tone",
  "Unwanted hair",
  "Body contouring",
] as const;
const Q2_VALUES = ["Normal", "Dry", "Oily", "Combination", "Sensitive"] as const;
const Q3_VALUES = [
  "Looking unnatural",
  "Recovery time",
  "Cost",
  "Not sure what I need",
  "I have no hesitations",
] as const;
const Q4_VALUES = [
  "Immediate (same day)",
  "Short-term (1-2 weeks)",
  "Gradual (1-3 months)",
  "Long-term investment",
] as const;
const Q5_VALUES = [
  "Yes, regularly",
  "Yes, a few times",
  "Once or twice",
  "Never, this is my first time",
] as const;

const AnswersSchema = z
  .object({
    q1: z.enum(Q1_VALUES),
    q2: z.enum(Q2_VALUES),
    q3: z.enum(Q3_VALUES),
    q4: z.enum(Q4_VALUES),
    q5: z.enum(Q5_VALUES),
  })
  .strict(); // Reject unknown keys.

// Optional lead capture payload. A4 sends it from the lead capture form;
// A5 will persist it to Airtable. For now, the server accepts and ignores it
// (logged at debug level only). Kept narrow: just name + email.
const LeadSchema = z
  .object({
    name: z.string().min(1).max(200),
    email: z.string().email().max(200),
  })
  .strict();

const RequestSchema = z
  .object({
    answers: AnswersSchema,
    lead: LeadSchema.optional(),
  })
  .strict();

type RequestBody = z.infer<typeof RequestSchema>;

// ---------------------------------------------------------------------------
// Response validation (defense in depth)
// ---------------------------------------------------------------------------

const TreatmentSchema = z.object({
  name: z.string().min(1).max(120),
  tagline: z.string().min(1).max(200),
  description: z.string().min(1).max(600),
  why: z.string().min(1).max(400),
  timeline: z.string().min(1).max(160),
  priceFrom: z.string().min(1).max(120),
});

const ResponseSchema = z.object({
  treatments: z.array(TreatmentSchema).min(2).max(3),
});

export type QuizResponse = z.infer<typeof ResponseSchema> & {
  meta?: { fallback?: boolean };
};

// ---------------------------------------------------------------------------
// Rate limit (in-memory, per-IP sliding window)
// ---------------------------------------------------------------------------

// Per PRD §3.2: 10 req/min/IP. In-memory Map is fine for a single-instance
// Vercel deployment; for multi-instance production, swap for Upstash/Redis.
// KNOWN LIMIT (Codex review): Vercel may run multiple isolated instances per
// region, multiplying the effective per-IP limit. Acceptable for portfolio demo
// where traffic is bounded; revisit before any real production traffic.
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX = 10;

// Bound the map so spoofed or one-shot IPs can't exhaust memory. When the map
// grows past MAX_TRACKED_IPS, drop the oldest (least-recently-touched) entry.
const MAX_TRACKED_IPS = 10_000;

type RateLimitEntry = { timestamps: number[]; lastSeen: number };
const rateLimitMap = new Map<string, RateLimitEntry>();

function checkRateLimit(ip: string): { allowed: boolean; retryAfterSec: number } {
  const now = Date.now();
  const entry = rateLimitMap.get(ip) ?? { timestamps: [], lastSeen: now };

  // Drop timestamps outside the sliding window.
  entry.timestamps = entry.timestamps.filter(
    (t) => now - t < RATE_LIMIT_WINDOW_MS,
  );

  if (entry.timestamps.length >= RATE_LIMIT_MAX) {
    const oldest = entry.timestamps[0] ?? now;
    const retryAfterSec = Math.max(
      1,
      Math.ceil((RATE_LIMIT_WINDOW_MS - (now - oldest)) / 1000),
    );
    entry.lastSeen = now;
    rateLimitMap.set(ip, entry);
    return { allowed: false, retryAfterSec };
  }

  entry.timestamps.push(now);
  entry.lastSeen = now;
  rateLimitMap.set(ip, entry);

  // Opportunistic eviction when the map grows too large. Map iteration is in
  // insertion order, so we trim from the front — which approximates LRU for
  // steady-state traffic. Cheap; runs at most once per request.
  if (rateLimitMap.size > MAX_TRACKED_IPS) {
    const overflow = rateLimitMap.size - MAX_TRACKED_IPS;
    let removed = 0;
    for (const key of rateLimitMap.keys()) {
      if (removed >= overflow) break;
      rateLimitMap.delete(key);
      removed++;
    }
  }

  return { allowed: true, retryAfterSec: 0 };
}

// ---------------------------------------------------------------------------
// Gemini schema + system prompt
// ---------------------------------------------------------------------------

// Schema-enforced JSON output. The model cannot violate the shape, which is
// strictly more reliable than relying on a prompt alone.
//
// NOTE (Codex review): `minItems` and `maxItems` on `@google/genai`'s `Schema`
// are typed as `string` even though OpenAPI-style JSON Schema uses numbers.
// Empirically the SDK accepts the string form and forwards it to the Gemini
// API, which understands both. We also re-validate the parsed response with
// Zod (using numeric `.min(2).max(3)`), so any drift between the Gemini schema
// and the Zod schema is caught before the response reaches the client.
const TreatmentResponseSchema = {
  type: Type.OBJECT,
  properties: {
    treatments: {
      type: Type.ARRAY,
      minItems: "2",
      maxItems: "3",
      items: {
        type: Type.OBJECT,
        properties: {
          name: {
            type: Type.STRING,
            description:
              "Treatment name as the clinic would present it (e.g. 'Injectables', 'RF Microneedling').",
          },
          tagline: {
            type: Type.STRING,
            description:
              "One-line editorial tagline in the clinic's voice. Calm, confident, never salesy.",
          },
          description: {
            type: Type.STRING,
            description:
              "2–3 sentence clinical description of what the treatment is and what it does.",
          },
          why: {
            type: Type.STRING,
            description:
              "Specific, personalised reason this treatment suits THIS patient's answers. Reference their concern, skin type, hesitation, timeline, or experience level.",
          },
          timeline: {
            type: Type.STRING,
            description:
              "When the patient can expect to see results (e.g. 'Visible in 3–7 days').",
          },
          priceFrom: {
            type: Type.STRING,
            description:
              "Starting price as the clinic would display it (e.g. 'From $14/unit Botox · Fillers from $750/syringe').",
          },
        },
        required: [
          "name",
          "tagline",
          "description",
          "why",
          "timeline",
          "priceFrom",
        ],
      },
    },
  },
  required: ["treatments"],
};

const SYSTEM_PROMPT = [
  "You are the clinical aesthetics consultant at Lumen Aesthetics, a discreet medical aesthetics studio in New York's Upper East Side.",
  "Your tone is cold-luxury editorial: calm, confident, restrained, never salesy. No superlatives, no hype, no exclamation marks.",
  "Match the clinic's voice exactly — the kind of language you'd see in a Vogue profile, not an ad.",
  "Recommend 2 to 3 treatments from the clinic's actual menu: Injectables, Laser Resurfacing, RF Microneedling, Body Sculpting, Skin Optimisation, Laser Hair Removal.",
  "Use the exact starting prices the clinic publishes: Injectables from $14/unit Botox and Fillers from $750/syringe; Laser Resurfacing from $350/session; RF Microneedling from $800/session; Body Sculpting from $1,200/session; Skin Optimisation from $275/session.",
  "Personalise the 'why' field to the patient's specific answers — reference their concern, skin type, hesitation, timeline, or experience level. Never write a generic 'why'.",
  "Never invent treatments the clinic doesn't offer. Never invent prices.",
  "Respond with JSON only — no prose, no preamble, no markdown fencing.",
].join(" ");

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

export async function POST(request: NextRequest): Promise<NextResponse> {
  // 1. Rate limit (distinct signal from fallback — return 429).
  const ip = getClientIp(request);
  const { allowed, retryAfterSec } = checkRateLimit(ip);
  if (!allowed) {
    return NextResponse.json(
      {
        error: "Too many requests. Please try again in a moment.",
      },
      {
        status: 429,
        headers: { "Retry-After": String(retryAfterSec) },
      },
    );
  }

  // 2. Parse + validate body. Cap body size BEFORE parsing so a malicious
  //    payload can't allocate a huge buffer. The quiz payload is bounded in
  //    practice (<1KB), so 4KB is a generous ceiling.
  const MAX_BODY_BYTES = 4_096;
  const contentLength = Number(request.headers.get("content-length") ?? "0");
  if (contentLength > MAX_BODY_BYTES) {
    return NextResponse.json(
      { error: "Invalid quiz submission." },
      { status: 413 },
    );
  }

  let body: RequestBody;
  try {
    const raw: unknown = await request.json();
    const parsed = RequestSchema.safeParse(raw);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid quiz submission." },
        { status: 400 },
      );
    }
    body = parsed.data;
  } catch {
    // Malformed JSON or empty body — never leak parse internals.
    return NextResponse.json(
      { error: "Invalid quiz submission." },
      { status: 400 },
    );
  }

  // 3. Call Gemini. On any throw or shape mismatch, fall back.
  const apiKey = process.env.GEMINI_API_KEY;

  // Lead capture is fire-and-forget. We do NOT await it because Airtable
  // latency (up to 5s timeout in the helper) would block the user from
  // seeing their results. The trade-off: on a cold start or in a serverless
  // environment that freezes the context immediately after the response is
  // sent, a small fraction of leads may be lost. This is acceptable per
  // PRD §3.3 — lead capture is non-critical and must never delay results.
  // Codex review: confirmed await pattern caused up-to-5s user-visible delay.
  queueLead(body.lead, body.answers);

  if (!apiKey) {
    return NextResponse.json(getFallbackRecommendations(body.answers));
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const userMessage =
      `My answers: ${body.answers.q1}; ${body.answers.q2} skin; ` +
      `biggest hesitation is ${body.answers.q3}; timeline is ${body.answers.q4}; ` +
      `prior experience: ${body.answers.q5}.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: userMessage,
      config: {
        systemInstruction: SYSTEM_PROMPT,
        responseMimeType: "application/json",
        responseSchema: TreatmentResponseSchema,
        temperature: 0.7,
        maxOutputTokens: 1024,
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error("Empty Gemini response");
    }

    let parsedJson: unknown;
    try {
      parsedJson = JSON.parse(text);
    } catch {
      throw new Error("Non-JSON Gemini response");
    }

    const validated = ResponseSchema.safeParse(parsedJson);
    if (!validated.success) {
      throw new Error("Gemini response did not match expected shape");
    }

    return NextResponse.json(validated.data satisfies QuizResponse);
  } catch (error) {
    // Never leak the error to the client. Server-side log only.
    // Sanitize: log a category and never the raw provider message. Provider
    // errors can include request IDs, quota details, model names, or partial
    // response text — none of which we want in operator-visible logs.
    const category = classifyError(error);
    console.error("[quiz] Gemini call failed, using fallback:", { category });
    return NextResponse.json(getFallbackRecommendations(body.answers));
  }
}

/**
 * Coarse-grained error classifier. Returns a short tag the operator can grep
 * for, without echoing the provider's message.
 */
function classifyError(error: unknown): string {
  if (!(error instanceof Error)) return "unknown";
  const msg = error.message.toLowerCase();
  if (msg.includes("api key") || msg.includes("auth")) return "auth";
  if (msg.includes("rate") || msg.includes("quota")) return "rate_limit";
  if (msg.includes("timeout") || msg.includes("etimedout")) return "timeout";
  if (msg.includes("empty")) return "empty_response";
  if (msg.includes("non-json") || msg.includes("json")) return "parse";
  if (msg.includes("shape") || msg.includes("schema")) return "schema";
  if (msg.includes("network") || msg.includes("econnrefused")) return "network";
  return "provider_error";
}

/**
 * Fire-and-forget the lead to Airtable. Errors are swallowed and logged
 * with a category tag — per PRD §3.3 and CLAUDE.md §5, lead capture
 * failures must never block the user from seeing their results.
 *
 * Not awaited by the caller. Trade-off: on serverless platforms that
 * freeze the execution context after the response is sent (e.g. Vercel),
 * a small fraction of leads may be dropped in flight. This is acceptable
 * because lead capture is non-critical and the alternative — awaiting —
 * delays the user by up to 5s on a slow Airtable response.
 *
 * Codex review: confirmed awaiting pattern caused up-to-5s user-visible
 * latency; this fire-and-forget form eliminates that delay.
 */
function queueLead(
  lead: { name: string; email: string } | undefined,
  answers: {
    q1: string;
    q2: string;
    q3: string;
    q4: string;
    q5: string;
  },
): void {
  if (!lead) return; // Skip path — no lead to send.

  // Use Promise chain so an unexpected throw doesn't crash the request.
  // Catch handlers log a coarse category only — never the raw error
  // message (which could include header/request context in some runtimes).
  // Codex review: original catch logged `error.message`, which can leak
  // sensitive request internals from the fetch implementation.
  postLeadToAirtable(lead, answers)
    .then((result) => {
      if (result.skipped) {
        // No Airtable credentials configured — expected in local dev.
        console.info("[quiz] Airtable not configured; lead not persisted");
        return;
      }
      if (!result.ok) {
        console.error("[quiz] Airtable lead capture failed:", {
          category: result.category ?? "unknown",
        });
      }
    })
    .catch(() => {
      // Final safety net. Don't echo the thrown value — see comment above.
      console.error("[quiz] Airtable lead capture threw:", {
        category: "unknown",
      });
    });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Best-effort client IP extraction. `x-forwarded-for` is set by Vercel and
 * other proxies; `x-real-ip` is a common fallback. Trim + take the first
 * hop. If neither is present, use a sentinel so the rate limiter still works.
 *
 * SECURITY NOTE (Codex review): we trust these headers because the production
 * deployment target (Vercel) overwrites client-supplied `x-forwarded-for` with
 * the real socket IP. If this app is ever deployed behind an untrusted proxy
 * that passes these headers through verbatim, the rate limiter becomes
 * spoofable — replace this with a verified-only proxy or move the limit to
 * the edge (Upstash + Vercel Edge Config).
 */
function getClientIp(request: NextRequest): string {
  const forwarded = request.headers.get("x-forwarded-for");
  if (forwarded) {
    const first = forwarded.split(",")[0]?.trim();
    if (first) return first;
  }
  const realIp = request.headers.get("x-real-ip")?.trim();
  if (realIp) return realIp;
  return "unknown";
}
